return { 
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  config = function ()
    local config = require("nvim-treesitter.configs")
    config.setup({
      auto_install = true,
      ensure_installed = {
        "ada",
        "bash",
        "bibtex",
        "c",
        "c_sharp",
        -- "cobol",
        "comment",
        "commonlisp",
        "cpp",
        "css",
        "csv",
        "cuda",
        "d",
        "diff",
        "dockerfile",
        "doxygen",
        "elixir",
        "elm",
        "erlang",
        "fish",
        "fortran",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "gnuplot",
        "go",
        "haskell",
        "html",
        "java",
        "javascript",
        "jsdoc",
        "json",
        "julia",
        "kotlin",
        -- "latex",
        "ledger",
        "llvm",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "nim",
        "nix",
        "ocaml",
        "ocaml_interface",
        "ocamllex",
        "odin",
        "pascal",
        "perl",
        "php",
        "printf",
        "python",
        "query",
        "r",
        "rst",
        "ruby",
        "rust",
        "scala",
        "ssh_config",
        "swift",
        "tmux",
        "toml",
        "typescript",
        "vala",
        "vim",
        "vimdoc",
        "yaml",
        "zathurarc",
        "zig",
      },
      sync_install = false,
      ignore_install = {
        "org", "latex"
      },
      highlight = {
        enable = true,
        disable = { "latex" },
      },
      indent = { enable = true },
    })
  end
}
